---
- name: Install the 'duo_unix' package
  package: name=duo_unix state=present

- name: Copy duo config into place.
  template:
    src: pam_duo.conf.j2
    dest: /etc/duo/pam_duo.conf
    owner: root
    group: root
    mode: 0600
